# See https://pre-commit.com for more information
default_stages: [ pre-commit, pre-push ]
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.0'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        name: poetry-export requirements
        args: ["-o", "app/requirements.txt", "--without-hashes"]
      - id: poetry-export
        name: poetry-export dev requirements
        args: ["-o", "app/requirements-dev.txt","--without-hashes", "--dev"]

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.10'
    hooks:
    - id: bandit
      additional_dependencies:
        - bandit[toml]
      args: ["-v", "-c", "pyproject.toml"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["-L", "selectin"]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.18
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-gfm
          - mdformat_frontmatter
          - linkify-it-py

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [ "--in-place", "--wrap-descriptions", "79" ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
#      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint

  -   repo: https://github.com/asottile/setup-cfg-fmt
      rev: v2.7.0
      hooks:
      -   id: setup-cfg-fmt

  - repo: https://github.com/pycqa/isort
    rev: '5.13.2'
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/hadialqattan/pycln
    rev: "v2.4.0"
    hooks:
    - id: pycln
      args: [ --config=setup.cfg ]


  - repo: https://github.com/pycqa/flake8
    rev: '7.1.1'
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==22.3.23
          - flake8-docstrings==1.6.0
          - flake8-import-order==0.18.1
          - flake8-print==4.0.0
          - flake8-async==22.3.10
          - pep8-naming==0.13.0
          - flake8-pytest-style==1.6.0

  - repo: https://github.com/asottile/yesqa
    rev: "v1.5.0"
    hooks:
    - id: yesqa

  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.18.0"
    hooks:
    - id: pyupgrade
      args: ["--py38-plus"]

  -   repo: https://github.com/Yelp/detect-secrets
      rev: v1.5.0
      hooks:
      -   id: detect-secrets

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: python-no-log-warn
      - id: python-no-eval
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.12.1"
    hooks:
    - id: mypy
      additional_dependencies:
        - sqlalchemy-stubs==0.4
        - types-requests==2.27.30
