"""Added is_active field to user model.

Revision ID: 3701fd619c16
Revises: 798540c2eae1
Create Date: 2022-06-06 23:08:51.764776
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3701fd619c16"
down_revision = "798540c2eae1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_active")
    # ### end Alembic commands ###
