# ...name, description and inputs as above
name: 'Prepare python environment'
description: 'Prepares the python environment for the project'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.10'
  poetry-version:
    description: 'Poetry version to use'
    required: true
    default: '1.1.13'
runs:
  using: "composite"
  steps:
    - run: |
        curl -O -sSL https://install.python-poetry.org/install-poetry.py
        python install-poetry.py -y --version  ${{ inputs.poetry-version }}
        echo "PATH=${HOME}/.poetry/bin:${PATH}" >> $GITHUB_ENV
        rm install-poetry.py
      shell: bash

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'

    - run: |
        # This is required to do as of @actions/checkout@v3 to prevent default action python (3.8) from being used
        poetry env use ${{ inputs.python-version }}
        poetry install
      shell: bash
