name: Pre-commit auto-update

#on:
#  schedule:
#    - cron: "0 18 * * *"
on: [push]
env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "1.1.13"
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare python environment
        # Use the location in the repository (without action.yml)
        uses: ./.github/actions/prepare-environment
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Reactivate poetry environment
        run: |
            poetry env use ${{ env.PYTHON_VERSION }}
      - run: |
        # This is required to do as of @actions/checkout@v3 to prevent default action python (3.8) from being used
        poetry run pre-commit autoupdate

      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
